spring.application.name=cinema-ticketing-backend
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=y.ashraf.ibrahim@gmail.com
spring.mail.password=agzd ibfr mqvs nunz
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


